---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: true
  ansible_verbosity: 4

platforms:
  - name: ubuntu-14.04
  - name: debian-8.1

suites:
  - name: default
