---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: true
  ansible_verbosity: 4

platforms:
  - name: ubuntu-14.04
  - name: debian-8.1
  - name: centos-7.1
    provisioner:
      enable_yum_epel: true

suites:
  - name: default
