---

# query the installed version to be used getting the schema path
- name: Get the sqlite_backend version
  yum_madison:
    name: 'pdns-backend-sqlite'
  register: pdns_sqlite_backend_version
  changed_when: False
  when: pdns_backends_sqlite3_databases is defined
