---
- name: Check pdns_repo_provider
  fail: msg="pdns_repo_provider is neither 'powerdns' nor 'os'"
  when: pdns_repo_provider not in ["os", "powerdns"]

- name: Install yum-plugin-priorities
  yum: name=yum-plugin-priorities state=installed
  when: pdns_repo_provider == "powerdns"

- name: Add PowerDNS repository
  get_url: url=https://repo.powerdns.com/repo-files/{{ansible_distribution | lower()}}-auth-{{pdns_repo_branch}}.repo dest=/etc/yum.repos.d/powerdns-auth-{{pdns_repo_branch}}.repo
  when: pdns_repo_provider == "powerdns"

- name: Install epel-release
  yum: name=epel-release update_cache=yes

- name: Install the PowerDNS package
  yum: name=pdns state=installed

- name: Install Geo module package
  yum: pkg=pdns-backend-geo state=installed
  when: item.startswith('geo') and not item.startswith('geoip')
  with_items: pdns_backends.keys()

- name: Install GeoIP module package
  yum: pkg=pdns-backend-geoip state=installed
  when: item.startswith('geoip')
  with_items: pdns_backends.keys()

- name: Install MySQL module package
  yum: pkg=pdns-backend-mysql state=installed
  when: item.startswith('gmysql')
  with_items: pdns_backends.keys()

- name: Install Postgresql module package
  yum: pkg=pdns-backend-postgresql state=installed
  when: item.startswith('gpgsql')
  with_items: pdns_backends.keys()

- name: Install gsqlite3 module package
  yum: pkg=pdns-backend-sqlite state=installed
  when: item.startswith('gsqlite3')
  with_items: pdns_backends.keys()

- name: Install ldap module package
  yum: pkg=pdns-backend-ldap state=installed
  when: item.startswith('ldap')
  with_items: pdns_backends.keys()

- name: Install lmdb module package
  yum: pkg=pdns-backend-lmdb state=installed
  when: item.startswith('lmdb')
  with_items: pdns_backends.keys()

- name: Install lua module package
  yum: pkg=pdns-backend-lua state=installed
  when: item.startswith('lua')
  with_items: pdns_backends.keys()

- name: Install mydns module package
  yum: pkg=pdns-backend-mydns state=installed
  when: item.startswith('mydns')
  with_items: pdns_backends.keys()

- name: Install pipe module package
  yum: pkg=pdns-backend-pipe state=installed
  when: item.startswith('pipe')
  with_items: pdns_backends.keys()

- name: Install remote module package
  yum: pkg=pdns-backend-remote state=installed
  when: item.startswith('remote')
  with_items: pdns_backends.keys()

- name: Install tinydns module package
  yum: pkg=pdns-backend-tinydns state=installed
  when: item.startswith('remote')
  with_items: pdns_backends.keys()
