---

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Setup PowerDNS Repo
  include: "repo-{{ ansible_os_family }}.yml"
  when: pdns_install_repo != ""
  tags:
    - install
    - repository

- name: Install EPEL (when required)
  include: install-epel.yml
  when: ansible_os_family == 'RedHat' and pdns_install_epel
  tags:
    - install

- name: Install PowerDNS
  package:
    name: pdns
    state: present
  tags:
    - install

- name: Install module package
  package:
    name: "{{ pdns_backends_dict[item.key.split(':')[0]] }}"
    state: installed
  when: pdns_backends_dict[item.key.split(':')[0]] is defined
  with_dict: "{{ pdns_backends }}"
  tags:
    - install 

- include: database-mysql.yml
  when: pdns_backends_mysql_credential is defined
  tags:
    - db
    - mysql 

- include: database-sqlite3-debian.yml
  static: false
  when: pdns_backends_sqlite3_databases is defined and ansible_os_family == "Debian"
  tags:
    - db
    - sqlite

- include: database-sqlite3-redhat.yml
  static: false
  when: pdns_backends_sqlite3_databases is defined and ansible_os_family == "RedHat"
  tags:
    - db
    - pdns-sqlite3-db

- include: configure.yml
  tags:
    - config

- name: Start and enable the PowerDNS service
  service:
    name: "{{ pdns_service_name }}"
    state: started
    enabled: true
  tags:
    - service

- name: Force handlers flush
  meta: flush_handlers
  when: pdns_flush_handlers
