---

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: "repo-{{ ansible_os_family }}.yml"
  when: pdns_install_repo != ""
  tags:
    - install
    - repository

- include: install-epel.yml
  when: ansible_os_family == 'RedHat' and pdns_install_epel
  tags:
    - install

- name: Install PowerDNS
  package:
    name: pdns
    state: present
  tags:
    - install

- name: Install module package
  package:
    name: "{{ pdns_backends_packages[item.key.split(':')[0]] }}"
    state: installed
  when: pdns_backends_dict[item.key.split(':')[0]] is defined
  with_dict: "{{ pdns_backends }}"
  tags:
    - install 

- include: "inspect-{{ ansible_os_family }}.yml"

- include: database-mysql.yml
  when: pdns_backends_mysql_credential is defined
  tags:
    - db
    - mysql 

- include: database-sqlite3.yml
  when: "{{ pdns_create_sqlite_database | length > 0 }}"
  tags:
    - db
    - sqlite

- include: configure.yml
  tags:
    - config

- name: Start and enable the PowerDNS service
  service:
    name: "{{ pdns_service_name }}"
    state: started
    enabled: true
  tags:
    - service

- name: Force handlers flush
  meta: flush_handlers
  when: pdns_flush_handlers
