---

- name: Import the PowerDNS APT Repository key
  apt_key:
    url: "{{ pdns_install_repo['gpg_key'] }}"
    id: "{{ pdns_install_repo['gpg_key_id'] | default('') }}"
    state: present

- name: Add the PowerDNS APT Repository
  apt_repository:
    repo: "{{ pdns_install_repo['apt_repo'] }}"
    state: present

- name: Pin the PowerDNS to the given APT Repository
  template:
    src: pdns.pin.j2
    dest: /etc/apt/preferences.d/pdns
